services:
  - type: web
    name: gradecalc
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn avg:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 